INFO:auth:Intento de login para usuario: info@0wlfunding.com
INFO:auth:Remember me activado: False
2025-01-02 19:00:59,888 INFO sqlalchemy.engine.Engine BEGIN (implicit)
INFO:sqlalchemy.engine.Engine:BEGIN (implicit)
2025-01-02 19:00:59,890 INFO sqlalchemy.engine.Engine SELECT users.id AS users_id, users.username AS users_username, users.email AS users_email, users.password_hash AS users_password_hash, users.is_active AS users_is_active, users.reset_code AS users_reset_code, users.reset_code_expires AS users_reset_code_expires 
FROM users 
WHERE users.username = %(username_1)s OR users.email = %(email_1)s 
 LIMIT %(param_1)s
INFO:sqlalchemy.engine.Engine:SELECT users.id AS users_id, users.username AS users_username, users.email AS users_email, users.password_hash AS users_password_hash, users.is_active AS users_is_active, users.reset_code AS users_reset_code, users.reset_code_expires AS users_reset_code_expires 
FROM users 
WHERE users.username = %(username_1)s OR users.email = %(email_1)s 
 LIMIT %(param_1)s
2025-01-02 19:00:59,891 INFO sqlalchemy.engine.Engine [generated in 0.00017s] {'username_1': 'info@0wlfunding.com', 'email_1': 'info@0wlfunding.com', 'param_1': 1}
INFO:sqlalchemy.engine.Engine:[generated in 0.00017s] {'username_1': 'info@0wlfunding.com', 'email_1': 'info@0wlfunding.com', 'param_1': 1}
ERROR:auth:Error en proceso de login: (psycopg2.errors.UndefinedColumn) column users.reset_code does not exist
LINE 1: ...assword_hash, users.is_active AS users_is_active, users.rese...
                                                             ^

[SQL: SELECT users.id AS users_id, users.username AS users_username, users.email AS users_email, users.password_hash AS users_password_hash, users.is_active AS users_is_active, users.reset_code AS users_reset_code, users.reset_code_expires AS users_reset_code_expires 
FROM users 
WHERE users.username = %(username_1)s OR users.email = %(email_1)s 
 LIMIT %(param_1)s]
[parameters: {'username_1': 'info@0wlfunding.com', 'email_1': 'info@0wlfunding.com', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-01-02 19:00:59,931 INFO sqlalchemy.engine.Engine ROLLBACK
INFO:sqlalchemy.engine.Engine:ROLLBACK
INFO:werkzeug:172.31.196.98 - - [02/Jan/2025 19:00:59] "POST /login?next=/settings HTTP/1.1" 200 -
INFO:werkzeug:172.31.196.98 - - [02/Jan/2025 19:01:00] "GET /static/css/style.css HTTP/1.1" 304 -
